---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Homework Guidelines

---

##### Github pre-requisites 

The following are pre-requisites for submitting the homework.

* We assume you already have a Github account and you are able to push/pull into Github. If not, please read [Lecture 01](https://kannan-kasthuri.github.io/Lecture_Files/Lecture_01.html).

* Claim your repository in Github - otherwise ask me and I will make you one.

---

##### README.txt

* As your first homework, you will create a README.txt file and push it into your repository. You need to constantly update this README.txt file as you work through the rest of the homeworks.

---

##### Rmd/.html files and organization

Throughout this course you will create R Markdown files and render it as html. Your markdown files should be named with an extension ".Rmd" or ".rmd". RStudio’s “Knit to HTML” button will compile the document for you to actual HTML and open a preview. 
You may want to read ahead [R Markdown](http://r4ds.had.co.nz/r-markdown.html) in the book R for Data Science. 

Make sure you organize your files really well (like naming appropriately) so it is easier for us to grade. Part of the grades will go for your ability to organize the code and the results for easier access and readability. 

---

#### How to submit homework?
