---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Homework 01 (due July,23, 2018, 5pm)

---

General guidelines for homeworks and how to submit them is given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html).

Accept your assignment in your GitHub. A repository will be created for you automagically.

Finish classwork/homework sections of Lecture 02 (R fundamentals 01: Elementary data types) and Lecture 03 (R fundamentals 02: Advanced data types and graphics) and push it through git (using the terminal or through RStudio). Please name your assignment as HW1_fistname_lastname. HW1 is due on Sept. 27, 5pm. If you have any questions about HW1, feel free to contact Yuhan, yuhan.hao at nyumc.org

You may use Rscript to complete this assignment. 

**Note**: You need to write a README.txt as given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html).

---

##### Report how you did it? - we really care for you

Feel free to write how this exercise worked for you and other things you read (related to this course) in README.txt. The reposotories are private and can be accessed ony by the admins. And also, this can be removed later.

---