---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Homework 05 (due Nov. 16, 2017, 5pm)

---

General guidelines for homeworks and how to submit them is given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html).

Accept your assignment in your GitHub. A repository will be created for you automagically.

The assignment requires you to complete the classwork/homework sections of the Data science 06 (Basic inference and linear regression) and Data science 07 (Advanced modeling) lectures. Directed insights will fetch credits.

**Note**: You need to write a README.txt and submit **both* .Rmd and html files as given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html) 

The due date is Nov. 16, 2017, 5pm. If you have any questions about this homework, feel free to contact Yuhan, yuhan.hao at nyumc.org

---

##### Report how you did it? - we really care for you

Feel free to write how this exercise worked for you and other things you read (related to this course) in README.txt. The reposotories are private and can be accessed ony by the admins. And also, this can be removed later.

---