---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Homework 03 (due Oct. 18, 2017, 12am)

---

General guidelines for homeworks and how to submit them is given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html).

Accept your assignment in your GitHub. A repository will be created for you automagically.

The assignment requires you to find the dataset of your choice and apply the principles of Exploratory Data Analysis (EDA) in the book R for Data Science. Click [here](http://r4ds.had.co.nz/exploratory-data-analysis.html) for the EDA chapter. Your work should demonstrate a thorough analysis of your data set, by framing questions and trying to answer them. Directed insights will fetch credits.

**Note**: You need to write a README.txt and submit **both* .Rmd and html files as given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html) 

The due date is Oct. 18, 2017, 12am. If you have any questions about this homework, feel free to contact Yuhan, yuhan.hao at nyumc.org

---

##### Report how you did it? - we really care for you

Feel free to write how this exercise worked for you and other things you read (related to this course) in README.txt. The reposotories are private and can be accessed ony by the admins. And also, this can be removed later.

---