---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Homework 02 (due July 30, 2018, 5pm)

---

General guidelines for homeworks and how to submit them is given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html).

1. Accept your assignment in your GitHub. A repository will be created for you automagically.

2. There are two parts to this homework: 

Finish classwork/homework sections of Lectures 04 (R fundamentals 03: Elements of prog., R Markdown) and Lecture 05 (Data science fundamentals 01: Visualize and explore) and push it through git (using the terminal or through RStudio). 


**Note**: You need to write a README.txt and submit **both* .Rmd and html files as given [here](https://kannan-kasthuri.github.io/Homework_Files/guidelines.html) 

The due date is July 30, 2018 5pm. If you have any questions about this homework, feel free to contact Emily, Emily.Dube at nyumc.org


---

##### Report how you did it? - we really care for you

Feel free to write how this exercise worked for you and other things you read (related to this course) in README.txt. The reposotories are private and can be accessed ony by the admins. And also, this can be removed later.

---