---
# title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Research Summary

---

If you are quickly looking for my pulication record - please click [here](https://kannan-kasthuri.github.io/publications.html). 

Research excites me as much as pedagogy. I have diverse academic interests - cancer biology, formal logic, physical theories, computing, mathematics to name a few. My contributions in science can be broadly classifed in the areas of computational physics and genomics. 

---

#### Contributions in computational physics

---

I started with mathematics, moved into computer science, writing a thesis in multipole algorithms. [Fast Multipole Method](https://en.wikipedia.org/wiki/Fast_multipole_method) is one of the top 10 algorithms of the 20th century introduced by [Prof. Greengard](https://en.wikipedia.org/wiki/Leslie_Greengard) of the Courant institute at NYU. My work focussed on generalizing the algorithm for higher order potentials and forces.


---

1. **Kasthuri Kannan**, Hemant Mahawar and Vivek Sarin, A Multipole Based Treecode using Spherical Harmonics for the Potentials of the Form $r^{-\lambda}$. _Lecture Notes in Computer Science_. 3514, pp. 107-114, May 2005.

    _Description_: Spherical harmonics are eigenfunctions of the Laplace-Beltrami operator in spherical coordinates. And hence they serve as orthogonal basis functions, which can be used to represent Coulomb-like potentials. We make use of this property to efficiently compute these potentials using ultraspherical (Gegenbauer) polynomials.

2. **Kasthuri Kannan** and Vivek Sarin, A Treecode for Accurate Force Calculations. _Lecture Notes in Computer Science_. 3991, pp. 92-99, May 2006.

    _Description_: Computing the forces in N-body simulations is of the order N^2. Treecodes present a fast approximation to such computations. However, accuracy in such computations are limited when using cartesian tensors. Spherical tensors provide greater accuracy for these simulations.

3. **Kasthuri Kannan** and Vivek Sarin, A Treecode for Potentials of the Form $r^{-\lambda}$, _International Journal of Computer Mathematics_. 84, 1249-1260, Jan. 2007.

    _Description_: This work presents a fast algorithm to compute potentials of the form r^{-lambda} that are used in molecular dynamics simulations. This is the exension of the first work above, where I describe the complete algorithm along with complexity analysis.

---

#### Contributions in biology/genomics

---

As a genomics scientist, my work focuses on developing and implementing bioinformatics algorithms as well as analyzing and interpreting biological data sets facilitating researcher’s experiments and hypothesis. I have extensive research experience analyzing and interpreting data from genomics/epigenetics experiments and have made vital contributions to several studies, especially in cancer genomics. One of my landmark discoveries, after I joined NYU is in pediatric brain cancer known as Pineoblastoma. I discovered significant number of copy number variations in a gene called PDE4DIP that holds an ancestral protein domain DUF1220 which is responsible for brain growth and function (revisions favorably received from _Nature Communications_). 

Another study of mine reveals key signaling pathways and genes responsible for Sudden Unexpected Death in Epilepsy (also known as SUDEP). Currently as an investigator at Genome Technology Center (GTC) in NYU, my research experience has broadned to encompass cancer epigenetics and I have developed algorithms to analyze ATAC-seq and ChIP-seq data. These pipleines are being extensively applied in several studies as I continue to collaborate with physician-scientists interpreting the results of the analysis.

My tenure at Memorial Sloan-Kettering Cancer Center (between 2011-2013), shaped me to perform critical roles in several genomics studies. My expertise in cancer genomics has been primarily focussed on brain tumors. One of my contributions (published in _Oncotarget_) in low-grade brain cancer called astrocytoma, identifies mutations in a gene called ATRX in 70% of the patients. In another study I helped in identifying three distinct gene expression groups of patients who contract astrocytoma, two of which harbors IDH mutations. Also, I was instrumental in identifying two melanoma patient subgroups who were treated with immunotherapy and this finding was published in _New England Journal of Medicine_. Further, my work on Adenoid Cystic Carcinoma in _Nature Genetics_ identifies clinically significant mutations and pathways through robust mutation calling and pathway analysis algorithms.

Further, I have developed a keen interest on tumor evolution and population genetics. My recent publication in _Letters in Biomathematics_, establishes a formula for inferring selection in tumors by making use of an advanced mathematical result called the Inverse Function Theorem. My long-term goal is to become a leader in genomics applying insights about evolutionary processes to the fields of cancer genetics and epigenetics at the same time collaboratively working with physician-scientists and computational biologists, on their hypothesis and interests.

---