---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Project Assesment

---

##### Final deliverable (due Sept. 1st 5pm)

Make an html document with directed insights based on Explore (E), Wrangle (W), Model(M), and Communicate (C) paradigm. You may use HANES/MIMIC3 datasets or any other datasets listed in the course [page](https://kannan-kasthuri.github.io/pda_summer_18.html). Your analysis should contain each aspect of EWPMC paradigm. The more meticulous/thorough you are in your analysis, you'll have a better chance of a good grade. The due date is **Sept. 1st** at 5pm. 

---

#### Project Grading Rubric (20% each)

---

You need to document and demonstrate all aspects of data science foundations discussed in the class.

1) Correctly apply tools and techniques of data preparation and wrangling 

    a. Missing data handling, joining, or other transformations, removing outliers etc.
    
    b. Gathering, spreading data (if needed)

2) Use Exploratory Data Analysis and `dplyr` transformation methods to identify structure and correlations in the data

3) Formulate questions and possible ways of analysis and visualization

    a. Identify appropriate visualization methods for analysis of your data set 
    
    b. Choose the right geoms for the questions at hand  
  
4) Correctly interpret results of analysis (clinical/biological significance)

    a. Demonstrate domain specific knowledge of clinical data
    
    b. Propose an hypothesis based on visualization and results

    c. Compare the usefulness of the obtained results/conclusions

5) Formulate appropriate plans for validation, further analysis, or to collect additional data needed. 

---

##### References

1. http://vita.had.co.nz/papers/layered-grammar.html

2. https://www.knime.com/about

---