---
title: "Classification"
author: "Sofia Nomikou"
date: "02/12/2018"
output: html_document
---

In this lab we are going to explore Classification techiques and apply them on biomedical data. We will study Logistic Regression and K-Nearest Neighbors. Let's begin!

## Our data
### For our lab today we are going to use the Wisconsin Breast Cancer data set. 
```{r}
library(mlbench)
data(BreastCancer)
str(BreastCancer)

BreastCancer$Cl.thickness <- as.numeric(as.character(BreastCancer$Cl.thickness))
BreastCancer$Cell.size <- as.numeric(as.character(BreastCancer$Cell.size))
BreastCancer$Cell.shape <- as.numeric(as.character(BreastCancer$Cell.shape))
BreastCancer$Marg.adhesion <- as.numeric(as.character(BreastCancer$Marg.adhesion))
BreastCancer$Epith.c.size <- as.numeric(as.character(BreastCancer$Epith.c.size))
BreastCancer$Bare.nuclei <- as.numeric(as.character(BreastCancer$Bare.nuclei))
BreastCancer$Bl.cromatin <- as.numeric(as.character(BreastCancer$Bl.cromatin))
BreastCancer$Normal.nucleoli <- as.numeric(as.character(BreastCancer$Normal.nucleoli))
BreastCancer$Mitoses <- as.numeric(as.character(BreastCancer$Mitoses))

str(BreastCancer)
```


```{r}
# Separate our data to train and test set - 80% train, 20% test
index <- sample(1:nrow(BreastCancer),round(0.80*nrow(BreastCancer)))
train <- BreastCancer[index,]
test <- BreastCancer[-index,]

train <- train[complete.cases(train),]
test <- test[complete.cases(test),]
```

## Logistic Regression

```{r}
# Fit logistic regression on the train data
glm.fit <- glm(Class ~ Cell.size + Cell.shape + Bare.nuclei + Cl.thickness + Marg.adhesion + Epith.c.size + Bl.cromatin + Normal.nucleoli + Mitoses , data = train, family = binomial)
summary(glm.fit)
# family = binomial to tell R to perform logistic regression and not some other type of 
# generalized model

# Variable importance
library(caret)
varImp(glm.fit)
```



```{r}
# How well does the model perform on the test data?
# Find probabilities for each data point in the test set
probabilities <- predict(glm.fit, newdata = test,type = "response")

# Convert to predictions
contrasts(test$Class)
predictions <- rep("benign", nrow(test))
predictions[probabilities >0.5] = "malignant"

# Create confusion matrix
confusion_matrix <- table(predictions, test$Class)
confusion_matrix
```
```{r}
#AUC
library(ROCR)
# Compute AUC for predicting Class with the model
prob <- predict(glm.fit, newdata=test, type="response")
pred <- prediction(prob, test$Class)
perf <- performance(pred, measure = "tpr", x.measure = "fpr")
plot(perf)

auc <- performance(pred, measure = "auc")
auc <- auc@y.values[[1]]
auc
```

## K-Nearest Neighbors
```{r}
library(class)
# Predict the labels of the test set simultaneously with the training of the model
prediction_knn <- knn(train[,2:10], test[,2:10], train$Class, k=4)
# Confusion matrix
table(prediction_knn, test$Class)

```



