---
# title: "Lecture 01"
# author: "Kasthuri Kannan"
# date: "Sept 07, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

### Introduction to the course (Sept. 07, 2017) 

---

#### Recorded Stream

---

<iframe width="560" height="315" src="https://www.youtube.com/embed/U36GaGt35p0" frameborder="0" allowfullscreen></iframe>

---

#### Register a GitHub account - Do this first! 

You are **required** to register for a free individual account at [GitHub](https://github.com/). You are encouraged to apply for [student developer pack](https://education.github.com/). They are free for students and awesome collection of tools and packages.

I will need your email id's you used for registration in GitHub to invite you to accept assignments. You will have your own private repositories where you'll deposit ("push" in git language) your classwork and homework for this course. Discussion among us for this course will be done at the [Discussion page](https://github.com/PDA-NYU-Fall-2017/Discussion/issues) in GitHub. You may also raise questions and issues by clicking "New issue" tab in this page.

**Don't freak out** if there are problems. That's pretty common when you are getting introduced to something new. Come to [office hours](https://kannan-kasthuri.github.io/pda.html), use our [Discussion page](https://github.com/PDA-NYU-Fall-2017/Discussion/issues) or ask for help.

---

#### R and RStudio

You can install R from its source page <a href="https://www.r-project.org/"target="_blank"> here</a>. I would suggest installing the precompiled binary for your OS.

Install RStudio desktop version from <a href="https://www.rstudio.com/products/RStudio/"target="_blank">here</a>. You need to install R first before installing RStudio for it to work.

RStudio comes with a text editor, so there is no need to install a separate stand-alone editor.

Even if you have a already existing installation of RStudio, I would **highly recommend** that you reinstall and upgrade to the most recent version. It is very easy to re-install RStudio which is evolving rapidly. 

* Once you installed RStudio, when you open it, you should see a screen something like [this](http://www.rstudio.com/wp-content/uploads/2014/04/rstudio-workbench.png). Of course, all the panes in your session will be empty.

* To check if everything is installed properly, type in `x <- 4 + 5` in your pane labelled Console. If you check the value of x by typing x in the console followed by a return, you should see the value 9 printed out.
  
If you upgrade R, you will need to update any packages you have installed. The following command in RStudio console (plus some extra-arguments perhaps), will update already installed packages:

`update.packages(ask = FALSE, checkBuilt = TRUE)`

---

#### How to add packages?

Use the following template:

`install.packages("package_name",dependencies = TRUE)` 

where "package_name" is the name of the package you want to install. For instance, if you want to install the package _tidyverse_, type 

`install.packages("tidyverse",dependencies = TRUE)`

in the console and you should have it.

---

#### Further resources/support

* RStudio support: https://support.rstudio.com/hc/en-us

* Getting help with R: https://support.rstudio.com/hc/en-us/articles/200717153-Getting-Help-with-R

* R FAQ: https://cran.r-project.org/doc/FAQ/R-FAQ.html

* R Instalation and admin: https://cran.r-project.org/doc/manuals/R-admin.html

---

#### Learn Git, Learn Git, Learn Git

*Terminal* is your friend. Getting comfortable using the terminal will go a long way in your career. 

We will be using Git extensively in the class and learning to access git through your terminal is necessary. If you are using a Mac, your terminal should be in _Applications -> Utilities -> Terminal_

Here is a good tutorial for Git: [Github Tutorial For Beginners](https://www.youtube.com/watch?v=0fKg7e37bQE) 

Here is another one (in windows): [Learn Git in 20 Minutes](https://www.youtube.com/watch?v=Y9XZQO1n_7c)

There are several good ones - just type 'git tutorial' in YouTube and find the one which you really like.

Working with RStudio, Git and Github - we will demo this in the class, but [here](http://happygitwithr.com/) is an excellent resource if you want to prepare ahead.

---

#### Selected materials and references

[The data science Venn diagram](http://drewconway.com/zia/2013/3/26/the-data-science-venn-diagram)

[Battle of the Data Science Venn Diagrams](http://www.kdnuggets.com/2016/10/battle-data-science-venn-diagrams.html)

[NYU's data science initiative](http://datascience.nyu.edu/what-is-data-science/)

[Why You May Want a Career in Data Science?](https://www.rtinsights.com/why-you-may-want-a-career-in-data-science/)

[Here’s a Retail Job That’s Still in High Demand: Data Scientist](https://www.bloomberg.com/news/articles/2017-08-21/here-s-a-retail-job-that-s-still-in-high-demand-data-scientist)

[Job Comparison – Data Scientist vs Data Engineer vs Statistician](https://www.analyticsvidhya.com/blog/2015/10/job-comparison-data-scientist-data-engineer-statistician/) - check out their cool infographics

[Introduction to Data Science](http://www.cs.tau.ac.il/~apartzin/ds2015/DS_CourseIntro.pdf)

[R Bloggers](https://www.r-bloggers.com/)

[Information management: Data domination](http://www.nature.com/nature/journal/v548/n7669/full/nj7669-613a.html?WT.mc_id=FBK_NatureNews&sf111552836=1)

---
