---
# title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
body {
text-align: justify}
figure figcaption {
    text-align: center;}
</style>

---

### Publications and Preprints 

---

Check out NYU's archive [here](http://library.med.nyu.edu/api/publications/?person=kannak01&sort=display_rank&in-biosketch=yes)

Also, **blue** font means equal/senior/last/first author contribution

---

[22] Lavanya Kannan, Tarjani Agarwal, Matija Snuderl, David Zagzag, Erik Sulman, Jason Huse, and <span style="color:blue"><b>Kasthuri Kannan</b></span>. Gibbs Process Determines Survival and Reveals Contact-Inhibition Genes in Glioblastoma Multiforme. Apr. 2019. bioRxiv 608414; doi: https://doi.org/10.1101/608414

[21] Martin Vaeth, Yin-Hu Wang, Miriam Eckstein, Jun Yang, Gregg Silverman, Rodrigo Lacruz, <span style="color:blue"><b>Kasthuri Kannan</b></span>, and Stefan Feske. Tissue resident and follicular Treg cell differentiation is regulated by CRAC channels. <span style="color:#e80c7a"> _Nature Communications_</span>. Mar. 2019. [PMID: 30862784](https://www.ncbi.nlm.nih.gov/pubmed/30862784/)

[20] Yuxiang Wang, Jie Yang, Aaron Wild, Wei Wu, Rachna Shah, Carla Danussi, Gregory Riggins, **Kasthuri Kannan**, Erik Sulman, Timothy Chan, and Jason Huse. G-quadruplex DNA drives genomic instability and represents a targetable molecular abnormality in ATRX-deficient malignant glioma. <span style="color:#e80c7a"> _Nature Communications_</span>. Feb. 2019. [PMID: 30808951](https://www.ncbi.nlm.nih.gov/pubmed/30808951)

[19] <span style="color:blue"><b>Matija Snuderl, Kasthuri Kannan</b></span> et al. (corresponding author: Matthias A. Karajannis). Recurrent homozygous deletion of DROSHA and microduplication of PDE4DIP containing the ancestral DUF1220 domain in pineoblastoma.<span style="color:#e80c7a"> _Nature Communications_</span>. Jul. 2018. [[PMID: 30030436]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6054684/) 

[18] <span style="color:blue"><b>Daniel Friedman, Kasthuri Kannan</b></span>, Arline Faustin, Seema Shroff, Cheddhi Thomas,  Adriana Heguy, Jonathan Serrano, Matija Snuderl, Orrin Devinsky. Cardiac Arrhythmia and Neuroexcitability Gene Mutations in resected brain tissue from patients with Sudden Unexpected Death in Epilepsy. <span style="color:#e80c7a"> _Nature Genomic Medicine_</span>. Mar. 2018. [[PMID: 29619247]](https://www.ncbi.nlm.nih.gov/pubmed/29619247)

[17] Carla Danussi, Promita Bose, Prasanna Parthasarathy, Pedro Silberman, John Van Arnam, Mark Vitucci, Oliver Tang, Adriana Heguy, Yuxiang Wang, Timothy Chan, Gregory Riggins, Erik Sulman, Frederick Lang, Chad Creighton, Benjamin Deneen, C Miller, David Picketts, <span style="color:blue"><b>Kasthuri Kannan</b></span>, and Jason Huse. Atrx inactivation drives disease-defining phenotypes in glioma cells of origin through global epigenomic remodeling. <span style="color:#e80c7a"> _Nature Communications_</span>. Mar. 2018. [[PMID: 29535300]](https://www.ncbi.nlm.nih.gov/pubmed/29535300)

[16]	David Capper et al. _somewhere in the middle_ **Kasthuri Kannan**, (corresponding author: Stefan M. Pfister). DNA methylation-based classification of human central nervous system tumors. <span style="color:#e80c7a"> _Nature_</span>. Mar. 2018. [[PMID: 29539639]](https://www.ncbi.nlm.nih.gov/pubmed/29539639)

[15] Fanok, Melania H; Sun, Amy; Fogli, Laura K; Narendran, Vijay; Eckstein, Miriam; **Kannan, Kasthuri**; Dolgalev, Igor; Lazaris, Charalampos; Heguy, Adriana; Laird, Mary E; Sundrud, Mark S; Liu, Cynthia; Kutok, Jeff; Lacruz, Rodrigo S; Latkowski, Jo-Ann; Aifantis, Iannis; Odum, Niels; Hymes, Kenneth B; Goel, Swati; Koralov, Sergei B. Role of dysregulated cytokine signaling and bacterial triggers in the pathogenesis of Cutaneous T Cell Lymphoma. <span style="color:#e80c7a"> _Journal of Investigative Dermatology_</span>. Nov. 2017. [[PMID: 29128259]](https://www.ncbi.nlm.nih.gov/pubmed/29128259)

[14]	<span style="color:blue"><b> Kasthuri Kannan</b></span> and Adriana Heguy. Why do mutant allele frequencies in oncogenes peak around .40 and rapidly decrease? <span style="color:#e80c7a"> _Letters In Biomathematics_</span>. Sept. 2016. [[Link]](http://dx.doi.org/10.1080/23737867.2016.1221328)

[13]	Snyder A, Makarov V, Merghoub T, Yuan J, Zaretsky JM, Desrichard A, Walsh LA, Postow MA, Wong P, Ho TS, Hollmann TJ, Bruggeman C, **Kasthuri Kannan**, Li Y, Elipenahli C, Liu C, Harbison CT, Wang L, Ribas A, Wolchok JD, Chan TA. Genetic basis for clinical response to CTLA-4 blockade in melanoma. <span style="color:#e80c7a"> _N Engl. J Med_</span>. Dec. 2014. [[PMID: 25409260]](https://www.ncbi.nlm.nih.gov/pubmed/25409260)

[12]	Marsha Reyngold, Sevin Turcan, Dilip Giri, **Kasthuri Kannan**, Logan A. Walsh et al. Remodeling of the Methylation Landscape in Breast Cancer Metastasis. <span style="color:#e80c7a"> _PLoS One_</span>. Aug. 2014. [[PMID: 25083786]](https://www.ncbi.nlm.nih.gov/pubmed/25083786)

[11]	Gerber NK,  Goenka A,  Turcan S,  Reyngold M,  Makarov V,  **Kasthuri Kannan**,  Beal K,  Omuro A,  Yamada Y,  Gutin P,  Brennan CW,  Huse JT, Chan TA. Transcriptional diversity of long-term glioblastoma survivors. <span style="color:#e80c7a"> _Neuro Oncol_</span>. Sept. 2014. [[PMID: 24662514]](https://www.ncbi.nlm.nih.gov/pubmed/24662514)

[10]	<span style="color:blue"> <b> Allen S. Ho, Kasthuri Kannan</b></span>, David Roy, Luc G.T. Morris, Nora Katabi, Stephanie Eng, et al. The Mutational Landscape of Adenoid Cystic Carcinoma. <span style="color:#e80c7a"> _Nature Genetics_</span>. July 2013. [[PMID: 23685749]](https://www.ncbi.nlm.nih.gov/pubmed/23685749)

[09]	Ian Ganly, Julio Ricarte Filho, Stephanie Eng, Ronald Ghossein, Luc G. T. Morris, Yupu Liang, Nicholas Socci, **Kasthuri Kannan**, Qianxing Mo, James A. Fagin, and Timothy A. Chan, Genomic Dissection of Hurthle Cell Carcinoma Reveals a Unique Class of Thyroid Malignancy. <span style="color:#e80c7a"> _The Journal of Clinical Endocrinology & Metabolism_</span>. May 2013. [[PMID: 23543667]](https://www.ncbi.nlm.nih.gov/pubmed/23543667)

[08]	Luc G.T. Morris, Andrew M. Kaufman, Yongxing Gong, Deepa Ramaswami, Logan A. Walsh, Sevin Turcan, Stephanie Eng, **Kasthuri Kannan**, Yilong Zou, et al., Frequent mutation of the Drosophila tumor suppressor-related gene FAT1 in multiple human cancers leads to aberrant Wnt activation. <span style="color:#e80c7a"> _Nature Genetics_</span>. Mar. 2013. [[PMID: 23354438]](https://www.ncbi.nlm.nih.gov/pubmed/23354438)

[07] <span style="color:blue"><b>Kasthuri Kannan</b></span>, Akiko Inagaki, Joachim Silber, Daniel Gorovets, Jianan Zhang, et al. Whole exome sequencing identifies ATRX mutation as a key molecular determinant in lower-grade glioma. <span style="color:#e80c7a"> _Oncotarget_</span>. Oct. 2012. [[PMID: 23104868]](https://www.ncbi.nlm.nih.gov/pubmed/23104868)

[06]	<span style="color:blue"><b> Daniel Gorovets, Kasthuri Kannan</b></span>, Edward R Kastenhuber, Nasrin Islam- doust, Carl Campos, et al. IDH Mutation and Neuroglial Developmental Features Define Clinically Distinct Subclasses of Lower-Grade Diffuse Astrocytic Glioma. <span style="color:#e80c7a"> _Clinical Cancer Research_</span>. May 2012. [[
PMID: 22415316]](https://www.ncbi.nlm.nih.gov/pubmed/22415316)

[05]	Amitabha Majumdar, Wanda  Colón Cesario, Erica White-Grindley, Huoqing Jiang, Fengzhen Ren, Mohammed  “Repon” Khan, Liying Li, Edward Man-Lik Choi, **Kasthuri Kannan**, Fengli Guo, Jay Unruh, Brian Slaughter, Kausik Si.  Critical Role of Amyloid-like Oligomers of Drosophila Orb2 in the Persistence of Memory. <span style="color:#e80c7a"> _Cell_</span>. Feb. 2012. [[PMID: 22284910]](https://www.ncbi.nlm.nih.gov/pubmed/22284910)

[04]	Yan Hao, Ningyi Xu, Andrew Box, Laura Schaefer, **Kasthuri Kannan**, et al. Nuclear cGMP-Dependent Kinase Regulates Gene Expression via Activity-Dependent Recruitment of a Conserved Histone Deacetylase Complex. <span style="color:#e80c7a"> _PLoS Genetics_</span>. May 2011. [[PMID: 21573134]](https://www.ncbi.nlm.nih.gov/pubmed/21573134)

[03]	<span style="color:blue"><b>Kasthuri Kannan</b></span> and Vivek Sarin, A Treecode for Potentials of the Form $r^{-\lambda}$, <span style="color:#e80c7a"> _International Journal of Computer Mathematics_</span>. 84, 1249-1260, Jan. 2007.

---

##### Conference proceedings

---


[02] <span style="color:blue"><b>Kasthuri Kannan</b></span> and Vivek Sarin, A Treecode for Accurate Force Calculations. <span style="color:#e80c7a"> _Lecture Notes in Computer Science_</span>. 3991, pp. 92-99, May 2006.

[01]	<span style="color:blue"><b>Kasthuri Kannan</b></span>, Hemant Mahawar and Vivek Sarin, A Multipole Based Treecode using Spherical Harmonics for the Potentials of the Form $r^{-\lambda}$. <span style="color:#e80c7a"> _Lecture Notes in Computer Science_</span>. 3514, pp. 107-114, May 2005.

---