---
# title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
body {
text-align: justify}
figure figcaption {
    text-align: center;}
</style>

---

### Publications and Preprints 
Last Updated: Friday, December 08, 2023

---

Check out PubMed archive [here](https://pubmed.ncbi.nlm.nih.gov/?term=kasthuri+kannan&sort=pubdate) (**note:** PubMed doesn't archive mathematical journals)

Also, **blue** font means equal/senior/last/first author contribution

---

---

##### Manuscripts in-review

---

[33] Prahlad Bhat, Michael Hwang, Afrooz Jahedi, Kanishka Sircar, and <span style="color:blue"><b>Kasthuri Kannan</b></span>. Spatial Point Process Model Predicts Survival in Clear Cell Renal Cell Carcinoma. <span style="color:#e80c7a">_MedRXiv_</span>. (https://doi.org/10.1101/2022.02.16.22271019)


---

##### Published/Accepted

---

[32] Gayatri Kumar, Renganayaki Krishna Pandurengan, Edwin Roger Parra, <span style="color:blue"><b>Kasthuri Kannan</b></span> and Cara Haymaker, Spatial modelling of the tumor microenvironment from multiplex immunofluorescence images: methods and applications. <span style="color:#e80c7a">_Frontiers in Immunology_</span> (accepted, yet to appear online).

[31] Tathiane M Malta, et al. (_as a part of the GLASS Consortium_), The epigenetic evolution of gliomas is determined by their IDH1 mutation status and correlates to treatment regimens. <span style="color:#e80c7a">_Cancer Research_</span> (accepted, yet to appear online).

[30] Edwin Roger Parra, Jiexin Zhang, Dzifa Yawa Duose, Edgar Gonzalez-Kozlova, Mary W. Redman, Hong Chen, Ganiraju C Manyam, Jianhua Zhang, Xingzhi Song, Rossana Lazcano, Mario Piubelli, Caddie Laberiano Fernandez, Frank Rojas, Baili Zhang, Len Taing, Aashna Jhaveri, Jacob Geisberg, Jen Altreuter, Franziska Michor, James Provencher, Joyce Yu, Ethan Cerami, Radim Moravec, **Kasthuri Kannan**, Rajyalakshmi Luthra, Gheath Al-Atrash, Hsin-Hui Huang, Hui Xie, Manishkumar Pate, Kai Nie, Jocelyn Harris, Kimberly Argueta, James Lindsay, Roshni Biswas, Stephen Van Nostrand, Seunghee Kim-Schulze, Jhanelle E. Gray, Roy Herbst, Ignacio I. Wistuba, Scott Gettinger, Karen Kelly, Lyudmila Bazhenova, Sacha Gnjatic, J. Jack Lee, Jianjun Zhang, Cara Haymaker. Multi-omics profiling of lung squamous cell carcinoma reveals immune signatures associated with checkpoint blockade response and resistance. <span style="color:#e80c7a">_Clinical Cancer Research_</span> (accepted, yet to appear online).

[29] Michal Marek Hoppe, Patrick Jaynes, Fan Shuangyi, Yanfen Peng, Phuong Mai Hoang, Liu Xin, Sanjay De Mel, Limei Poon, Esther Chan, Joanne Lee, Choon Kiat Ong, Tiffany Tang, Soon Thye Lim, Chandramouli Nagarajan, Nicholas Francis Grigoropoulos, Soo-Yong Tan, Susan Swee-Shan Hue, Sheng-Tsung Chang, Shih-Sung Chuang, Shaoying Li, Joseph D. Khoury, Hyungwon Choi, Carl Harris III, Alessia Bottos, Laura J. Gay, Hendrik F. P. Runge, Ilias Moutsopoulos, Irina Mohorianu, Daniel J. Hodson, Pedro Farinha, Anja Mottok, David W. Scott, Gayatri Kumar, **Kasthuri Kannan**, Wee-Joo Chng, Yen Lin Chee, Siok-Bian Ng, Claudio Tripodo, Anand D. Jeyasekharan. Patterns of oncogene co-expression at single cell resolution in cancer influence survival. <span style="color:#e80c7a">_Cancer Discovery_</span>. May 2023. [[PMID: 37071673]](https://pubmed.ncbi.nlm.nih.gov/37071673/)

[28]  Jahedi A, Kumar G, Kannan L, Agarwal T, Huse J, Bhat K, <span style="color:blue"><b>Kannan K</b></span>. Gibbs Process Distinguishes Survival and Reveals Contact-Inhibition Genes in Glioblastoma Multiforme. <span style="color:#e80c7a"> _PLoS One_</span>. Feb. 2023. [[PMID: 36795646]](https://pubmed.ncbi.nlm.nih.gov/36795646/)

[27] Varn FS et al. (_as a part of the GLASS consortium_). Glioma progression is shaped by genetic evolution and microenvironment interactions. <span style="color:#e80c7a">_Cell_</span>. Jun. 2022. [[PMID: 35649412]](https://pubmed.ncbi.nlm.nih.gov/35649412/)

[26] Sun X, Zhai J, Sun B, Parra ER, Jiang M, Ma W, Wang J, Kang AM, **Kannan K**, Pandurengan R, Zhang S, Solis LM, Haymaker CL, Raso MG, Mendoza Perez J, Sahin AA, Wistuba II, Yam C, Litton JK, Yang F. Effector memory cytotoxic CD3+/CD8+/CD45RO+ T cell predicts good survival with less risk to recurrence in triple-negative breast cancer. <span style="color:#e80c7a">_Modern Pathology_</span>. May 2022. [[PMID:34839351]](https://pubmed.ncbi.nlm.nih.gov/34839351/)

[25] Yam C, Yen EY, Chang JT, Bassett RL, Alatrash G, Garber H, Huo L, Yang F, Philips AV, Ding QQ, Lim B, Ueno NT, **Kannan K**, Sun X, Sun B, Parra Cuentas ER, Symmans WF, White JB, Ravenberg E, Seth S, Guerriero JL, Rauch GM, Damodaran S, Litton JK, Wargo JA, Hortobagyi GN, Futreal A, Wistuba II, Sun R, Moulder SL, Mittendorf EA. Immune Phenotype and Response to Neoadjuvant Therapy in Triple-Negative Breast Cancer. <span style="color:#e80c7a">_Clin Cancer Research_</span>. Jul. 2021. [[PMID: 34253579]](https://pubmed.ncbi.nlm.nih.gov/34253579/)

[24] Scherwitzl I, Opp S, Hurtado AM, Pampeno C, Loomis C, **Kannan K**, Yu M, Meruelo D. Sindbis Virus with Anti-OX40 Overcomes the Immunosuppressive Tumor Microenvironment of Low-Immunogenic Tumors. <span style="color:#e80c7a"> _Molecular Therapy - Oncolytics_</span>. Jun. 2020. [[PMID: 32478167]](https://pubmed.ncbi.nlm.nih.gov/32478167/)

[23] Dhanasekaran R, Baylot V, Kim M, Kuruvilla S, Bellovin DI, Adeniji N, Rajan Kd A, Lai I, Gabay M, Tong L, Krishnan M, Park J, Hu T, Barbhuiya MA, Gentles AJ, **Kannan K**, Tran PT, Felsher DW. MYC and Twist1 cooperate to drive metastasis by eliciting crosstalk between cancer and innate immunity. <span style="color:#e80c7a"> _eLife_</span>. Jan. 2020. [[PMID: 31933479]](https://pubmed.ncbi.nlm.nih.gov/31933479/)

[22] Hao Y, Ruiz R, Yang L, Neto AG, Amin MR, Kelly D, Achlatis S, Roof S, Bing R, **Kannan K**, Brown SM, Pei Z, Branski RC. Mitochondrial somatic mutations and lack of viral genomic variation in recurrent respiratory papillomatosis. <span style="color:#e80c7a"> _Scientific Reports_</span>. Oct. 2019. [[PMID: 31719597]](https://www.ncbi.nlm.nih.gov/pubmed/31719597)

[21] Vaeth M, Wang YH, Eckstein M, Yang J, Silverman GJ, Lacruz RS, <span style="color:blue"><b>Kannan K</b></span>, Feske S. Tissue resident and follicular Treg cell differentiation is regulated by CRAC channels. <span style="color:#e80c7a"> _Nature Communications_</span>. Mar. 2019. [[PMID: 30862784]](https://www.ncbi.nlm.nih.gov/pubmed/30862784/)

[20] Wang Y, Yang J, Wild AT, Wu WH, Shah R, Danussi C, Riggins GJ, **Kannan K**, Sulman EP, Chan TA, Huse JT. G-quadruplex DNA drives genomic instability and represents a targetable molecular abnormality in ATRX-deficient malignant glioma. <span style="color:#e80c7a"> _Nature Communications_</span>. Feb. 2019. [[PMID: 30808951]](https://www.ncbi.nlm.nih.gov/pubmed/30808951)

[19] <span style="color:blue"><b>Snuderl M, Kannan K</b></span>, Pfaff E, Wang S, Stafford JM, Serrano J, Heguy A, Ray K, Faustin A, Aminova O, Dolgalev I, Stapleton SL, Zagzag D, Chiriboga L, Gardner SL, Wisoff JH, Golfinos JG, Capper D, Hovestadt V, Rosenblum MK, Placantonakis DG, LeBoeuf SE, Papagiannakopoulos TY, Chavez L, Ahsan S, Eberhart CG, Pfister SM, Jones DTW, Karajannis MA. Recurrent homozygous deletion of DROSHA and microduplication of PDE4DIP containing the ancestral DUF1220 domain in pineoblastoma.<span style="color:#e80c7a"> _Nature Communications_</span>. Jul. 2018. [[PMID: 30030436]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6054684/) 

[18] <span style="color:blue"><b>Friedman D, Kannan K</b></span>, Faustin A, Shroff S, Thomas C, Heguy A, Serrano J, Snuderl M, Devinsky O. Cardiac Arrhythmia and Neuroexcitability Gene Mutations in resected brain tissue from patients with Sudden Unexpected Death in Epilepsy. <span style="color:#e80c7a"> _Nature Genomic Medicine_</span>. Mar. 2018. [[PMID: 29619247]](https://www.ncbi.nlm.nih.gov/pubmed/29619247)

[17] Danussi C, Bose P, Parthasarathy PT, Silberman PC, Van Arnam JS, Vitucci M, Tang OY, Heguy A, Wang Y, Chan TA, Riggins GJ, Sulman EP, Lang FF, Creighton CJ, Deneen B, Miller CR, Picketts DJ, <span style="color:blue"><b>Kannan K</b></span>, Huse JT. Atrx inactivation drives disease-defining phenotypes in glioma cells of origin through global epigenomic remodeling. <span style="color:#e80c7a"> _Nature Communications_</span>. Mar. 2018. [[PMID: 29535300]](https://www.ncbi.nlm.nih.gov/pubmed/29535300)

[16] Capper D, Jones DTW, Sill M, Hovestadt V, Schrimpf D, Sturm D, Koelsche C, Sahm F, Chavez L, Reuss DE, Kratz A, Wefers AK, Huang K, Pajtler KW, Schweizer L, Stichel D, Olar A, Engel NW, Lindenberg K, Harter PN, Braczynski AK, Plate KH, Dohmen H, Garvalov BK, Coras R, Hölsken A, Hewer E, Bewerunge-Hudler M, Schick M, Fischer R, Beschorner R, Schittenhelm J, Staszewski O, Wani K, Varlet P, Pages M, Temming P, Lohmann D, Selt F, Witt H, Milde T, Witt O, Aronica E, Giangaspero F, Rushing E, Scheurlen W, Geisenberger C, Rodriguez FJ, Becker A, Preusser M, Haberler C, Bjerkvig R, Cryan J, Farrell M, Deckert M, Hench J, Frank S, Serrano J, **Kannan K**, Tsirigos A, Brück W, Hofer S, Brehmer S, Seiz-Rosenhagen M, Hänggi D, Hans V, Rozsnoki S, Hansford JR, Kohlhof P, Kristensen BW, Lechner M, Lopes B, Mawrin C, Ketter R, Kulozik A, Khatib Z, Heppner F, Koch A, Jouvet A, Keohane C, Mühleisen H, Mueller W, Pohl U, Prinz M, Benner A, Zapatka M, Gottardo NG, Driever PH, Kramm CM, Müller HL, Rutkowski S, von Hoff K, Frühwald MC, Gnekow A, Fleischhack G, Tippelt S, Calaminus G, Monoranu CM, Perry A, Jones C, Jacques TS, Radlwimmer B, Gessi M, Pietsch T, Schramm J, Schackert G, Westphal M, Reifenberger G, Wesseling P, Weller M, Collins VP, Blümcke I, Bendszus M, Debus J, Huang A, Jabado N, Northcott PA, Paulus W, Gajjar A, Robinson GW, Taylor MD, Jaunmuktane Z, Ryzhova M, Platten M, Unterberg A, Wick W, Karajannis MA, Mittelbronn M, Acker T, Hartmann C, Aldape K, Schüller U, Buslei R, Lichter P, Kool M, Herold-Mende C, Ellison DW, Hasselblatt M, Snuderl M, Brandner S, Korshunov A, von Deimling A, Pfister SM. DNA methylation-based classification of human central nervous system tumors. <span style="color:#e80c7a"> _Nature_</span>. Mar. 2018. [[PMID: 29539639]](https://www.ncbi.nlm.nih.gov/pubmed/29539639)

[15] Fanok MH, Sun A, Fogli LK, Narendran V, Eckstein M, **Kannan K**, Dolgalev I, Lazaris C, Heguy A, Laird ME, Sundrud MS, Liu C, Kutok J, Lacruz RS, Latkowski JA, Aifantis I, Ødum N, Hymes KB, Goel S, Koralov SB. Role of dysregulated cytokine signaling and bacterial triggers in the pathogenesis of Cutaneous T Cell Lymphoma. <span style="color:#e80c7a"> _Journal of Investigative Dermatology_</span>. Nov. 2017. [[PMID: 29128259]](https://www.ncbi.nlm.nih.gov/pubmed/29128259)

[14] <span style="color:blue"><b> Kasthuri Kannan</b></span> and Adriana Heguy. Why do mutant allele frequencies in oncogenes peak around .40 and rapidly decrease? <span style="color:#e80c7a"> _Letters In Biomathematics_</span>. Sept. 2016. [[Link]](http://dx.doi.org/10.1080/23737867.2016.1221328)

[13] Snyder A, Makarov V, Merghoub T, Yuan J, Zaretsky JM, Desrichard A, Walsh LA, Postow MA, Wong P, Ho TS, Hollmann TJ, Bruggeman C, **Kannan K**, Li Y, Elipenahli C, Liu C, Harbison CT, Wang L, Ribas A, Wolchok JD, Chan TA. Genetic basis for clinical response to CTLA-4 blockade in melanoma. <span style="color:#e80c7a"> _N Engl. J Med_</span>. Dec. 2014. [[PMID: 25409260]](https://www.ncbi.nlm.nih.gov/pubmed/25409260)

[12] Reyngold M, Turcan S, Giri D, **Kannan K**, Walsh LA, Viale A, Drobnjak M, Vahdat LT, Lee W, Chan TA. Remodeling of the Methylation Landscape in Breast Cancer Metastasis. <span style="color:#e80c7a"> _PLoS One_</span>. Aug. 2014. [[PMID: 25083786]](https://www.ncbi.nlm.nih.gov/pubmed/25083786)

[11] Gerber NK, Goenka A, Turcan S, Reyngold M, Makarov V, **Kannan K**, Beal K, Omuro A, Yamada Y, Gutin P, Brennan CW, Huse JT, Chan TA. Transcriptional diversity of long-term glioblastoma survivors. <span style="color:#e80c7a"> _Neuro Oncol_</span>. Sept. 2014. [[PMID: 24662514]](https://www.ncbi.nlm.nih.gov/pubmed/24662514)

[10] <span style="color:blue"><b>Ho AS, Kannan K</b></span>, Roy DM, Morris LG, Ganly I, Katabi N, Ramaswami D, Walsh LA, Eng S, Huse JT, Zhang J, Dolgalev I, Huberman K, Heguy A, Viale A, Drobnjak M, Leversha MA, Rice CE, Singh B, Iyer NG, Leemans CR, Bloemena E, Ferris RL, Seethala RR, Gross BE, Liang Y, Sinha R, Peng L, Raphael BJ, Turcan S, Gong Y, Schultz N, Kim S, Chiosea S, Shah JP, Sander C, Lee W, Chan TA. The Mutational Landscape of Adenoid Cystic Carcinoma. <span style="color:#e80c7a"> _Nature Genetics_</span>. July 2013. [[PMID: 23685749]](https://www.ncbi.nlm.nih.gov/pubmed/23685749)

[09] Ganly I, Ricarte Filho J, Eng S, Ghossein R, Morris LG, Liang Y, Socci N, **Kannan K**, Mo Q, Fagin JA, Chan TA. Genomic Dissection of Hurthle Cell Carcinoma Reveals a Unique Class of Thyroid Malignancy. <span style="color:#e80c7a"> _The Journal of Clinical Endocrinology & Metabolism_</span>. May 2013. [[PMID: 23543667]](https://www.ncbi.nlm.nih.gov/pubmed/23543667)

[08] Morris LG, Kaufman AM, Gong Y, Ramaswami D, Walsh LA, Turcan Ş, Eng S, **Kannan K**, Zou Y, Peng L, Banuchi VE, Paty P, Zeng Z, Vakiani E, Solit D, Singh B, Ganly I, Liau L, Cloughesy TC, Mischel PS, Mellinghoff IK, Chan TA. Frequent mutation of the Drosophila tumor suppressor-related gene FAT1 in multiple human cancers leads to aberrant Wnt activation. <span style="color:#e80c7a"> _Nature Genetics_</span>. Mar. 2013. [[PMID: 23354438]](https://www.ncbi.nlm.nih.gov/pubmed/23354438)

[07] <span style="color:blue"><b>Kannan K</b></span>, Inagaki A, Silber J, Gorovets D, Zhang J, Kastenhuber ER, Heguy A, Petrini JH, Chan TA, Huse JT. Whole exome sequencing identifies ATRX mutation as a key molecular determinant in lower-grade glioma. <span style="color:#e80c7a"> _Oncotarget_</span>. Oct. 2012. [[PMID: 23104868]](https://www.ncbi.nlm.nih.gov/pubmed/23104868)

[06] <span style="color:blue"><b>Gorovets D, Kannan K</b></span>, Shen R, Kastenhuber ER, Islamdoust N, Campos C, Pentsova E, Heguy A, Jhanwar SC, Mellinghoff IK, Chan TA, Huse JT. IDH Mutation and Neuroglial Developmental Features Define Clinically Distinct Subclasses of Lower-Grade Diffuse Astrocytic Glioma. <span style="color:#e80c7a"> _Clinical Cancer Research_</span>. May 2012. [[PMID: 22415316]](https://www.ncbi.nlm.nih.gov/pubmed/22415316)

[05] Majumdar A, Cesario WC, White-Grindley E, Jiang H, Ren F, Khan MR, Li L, Choi EM, **Kannan K**, Guo F, Unruh J, Slaughter B, Si K. Critical Role of Amyloid-like Oligomers of Drosophila Orb2 in the Persistence of Memory. <span style="color:#e80c7a"> _Cell_</span>. Feb. 2012. [[PMID: 22284910]](https://www.ncbi.nlm.nih.gov/pubmed/22284910)

[04] Hao Y, Xu N, Box AC, Schaefer L, **Kannan K**, Zhang Y, Florens L, Seidel C, Washburn MP, Wiegraebe W, Mak HY. Nuclear cGMP-Dependent Kinase Regulates Gene Expression via Activity-Dependent Recruitment of a Conserved Histone Deacetylase Complex. <span style="color:#e80c7a"> _PLoS Genetics_</span>. May 2011. [[PMID: 21573134]](https://www.ncbi.nlm.nih.gov/pubmed/21573134)

[03] <span style="color:blue"><b>Kasthuri Kannan</b></span> and Vivek Sarin, A Treecode for Potentials of the Form $r^{-\lambda}$, <span style="color:#e80c7a"> _International Journal of Computer Mathematics_</span>. 84, 1249-1260, Jan. 2007.

---

##### Conference proceedings

---


[02] <span style="color:blue"><b>Kasthuri Kannan</b></span> and Vivek Sarin, A Treecode for Accurate Force Calculations. <span style="color:#e80c7a"> _Lecture Notes in Computer Science_</span>. 3991, pp. 92-99, May 2006.

[01] <span style="color:blue"><b>Kasthuri Kannan</b></span>, Hemant Mahawar and Vivek Sarin, A Multipole Based Treecode using Spherical Harmonics for the Potentials of the Form $r^{-\lambda}$. <span style="color:#e80c7a"> _Lecture Notes in Computer Science_</span>. 3514, pp. 107-114, May 2005.

---